[project]
name = "livekit-outbound"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chris Kulpa", email = "chriskulpamlb@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "livekit-agents>=1.8.1",
    "livekit-api>=1.2.1",
    "livekit-plugins-cartesia>=1.8.1",
    "livekit-plugins-deepgram>=1.8.1",
    "livekit-plugins-openai>=1.8.1",
    "livekit-plugins-silero>=1.8.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
livekit-outbound = "livekit_outbound:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
